name: Blog bl0g  b10g
url: https://FacundoAcevedo.github.io
description: Cosas que no me tengo que ovlidar


permalink: /:day/:month/:year/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

theme: jekyll-theme-midnight